// S6-005 integration — read-only loopback bridge to the preserved Node MCP/CAD
// server. Proves:
//   1. The bridge spawns the preserved server via scripts/mcp-entry.mjs on a
//      random localhost port with a per-session token (no fixed port).
//   2. Get-only surface round-trips always: /health, /objects, /object?name=,
//      /mesh/<name>, /project — all through the bridge token.
//   3. No data loss: a fixture 3MF converted to STL (via the repo's own
//      scripts/import-3mf-mesh.mjs) is preloaded through the bridge; the bridge
//      mesh read matches the direct preserved-server read byte-for-byte and the
//      source STL triangle/vertex data exactly.
//   4. Zero write paths over the bridge (R0): a non-GET method → 405; unknown
//      GET → 404.
//   5. Stale/absent upstream never crashes: killing the child marks the bridge
//      `unavailable` on every route (no silent fallback).
//
// The 3MF fixture tests/fixtures/slab-20mm.3mf is generated by
// tools/3mf/make-slab-3mf.mjs (committed); the STL next to it is produced by
// scripts/import-3mf-mesh.mjs with default plate centering and committed so the
// test is deterministic and offline. The child server auto-builds dist/ on a
// fresh clone (mcp-entry.mjs), so this test runs before the build gate.
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { test } from "node:test";
import { startBridge } from "../../scripts/loopback-bridge.mjs";

const root = resolve(import.meta.dirname, "..", "..");
const slab3mf = resolve(root, "tests", "fixtures", "slab-20mm.3mf");
const slabStl = resolve(root, "tests", "fixtures", "slab-20mm.stl");

// Minimal binary STL reader (little-endian: 80-byte header, uint32 tri count,
// then per-triangle 12 floats + uint16 attribute).
function readBinaryStl(filePath) {
  const buf = readFileSync(filePath);
  const count = buf.readUInt32LE(80);
  const positions = [];
  const tris = [];
  let offset = 84;
  for (let i = 0; i < count; i++) {
    const v = () => {
      const x = buf.readFloatLE(offset);
      const y = buf.readFloatLE(offset + 4);
      const z = buf.readFloatLE(offset + 8);
      offset += 12;
      positions.push(x, y, z);
      return positions.length / 3 - 1;
    };
    offset += 12; // skip normal
    const a = v();
    const b = v();
    const c = v();
    offset += 2; // skip attribute byte count
    tris.push({ a, b, c });
  }
  return { positions, tris };
}

async function bridgeGet(base, token, pathname, { method = "GET" } = {}) {
  const res = await fetch(`${base}${pathname}`, {
    method,
    headers: { "X-Bridge-Token": token },
  });
  const data = await res.json().catch(() => ({}));
  return { status: res.status, data };
}

// Direct preserved-server read used as the oracle (same upstream the bridge
// proxies, exercised without the bridge so the test proves identity).
async function directUpstream(handle, pathname, { method = "GET", body } = {}) {
  const base = handle.upstreamUrl.split("?")[0].replace(/\/+$/, "");
  const res = await fetch(`${base}${pathname}`, {
    method,
    headers: {
      "X-Cad-Token": handle.upstreamToken,
      ...(body ? { "Content-Type": "application/json" } : {}),
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const data = await res.json().catch(() => ({}));
  return { status: res.status, data };
}

// bridge.url carries the token in the query string (?token=...) — split it to get
// the clean base used for the header-authenticated routes (no trailing slash).
function bridgeBase(url) {
  return url.split("?")[0].replace(/\/+$/, "");
}

test(
  "S6-005 read-only bridge round-trips a fixture 3MF without data loss",
  { timeout: 60000 },
  async () => {
    // Preload the converted 3MF (STL form) through the bridge input path.
    const bridge = await startBridge({ inputPath: slabStl });
    const base = bridgeBase(bridge.url);
    try {
      // Random loopback port + per-session bridge token.
      assert.equal(typeof bridge.port, "number");
      assert.equal(bridge.url.startsWith("http://127.0.0.1:"), true);
      assert.match(bridge.token, /^[a-f0-9]{32}$/);
      assert.match(bridge.upstreamToken, /^[a-f0-9]{32}$/);
      assert.equal(bridge.state, "ready");

      // Get-only surface: /health.
      const health = await bridgeGet(base, bridge.token, "/health");
      assert.equal(health.status, 200);
      assert.equal(health.data.ok, true);
      assert.equal(health.data.state, "ready");

      // /objects — object list identical to a direct server read.
      const objects = await bridgeGet(base, bridge.token, "/objects");
      assert.equal(objects.status, 200);
      assert.equal(objects.data.ok, true);
      assert.ok(Array.isArray(objects.data.objects));
      assert.equal(objects.data.objects.length, 1);
      const name = objects.data.objects[0].name;
      assert.equal(name, "slab-20mm");

      // /object?name= — meshInfo via the bridge matches the direct server read.
      const obj = await bridgeGet(base, bridge.token, `/object?name=${encodeURIComponent(name)}`);
      assert.equal(obj.status, 200);
      assert.equal(obj.data.ok, true);
      assert.equal(obj.data.object.name, name);
      // The preserved importer repacks positions per triangle: a 12-triangle
      // slab loads as 36 vertices (3 per triangle), 12 triangles.
      assert.equal(obj.data.object.vertices, 36);
      assert.equal(obj.data.object.triangles, 12);
      assert.equal(obj.data.object.sizeMm.x, 20);
      assert.equal(obj.data.object.sizeMm.y, 20);
      assert.equal(obj.data.object.sizeMm.z, 20);
      const directObj = await directUpstream(bridge, "/api/object", {
        method: "POST",
        body: { name },
      });
      assert.deepEqual(obj.data.object, directObj.data.object);

      // /mesh/<name> — mesh payload through the bridge is EXACTLY the STL data
      // that originated from the 3MF fixture (no data loss) and equals the
      // direct preserved-server read.
      const mesh = await bridgeGet(base, bridge.token, `/mesh/${encodeURIComponent(name)}`);
      assert.equal(mesh.status, 200);
      assert.equal(mesh.data.ok, true);
      assert.equal(mesh.data.name, name);
      assert.equal(mesh.data.tris.length, 12);
      assert.equal(mesh.data.positions.length, 36 * 3);
      // Direct server read (oracle) vs bridge read.
      const directMesh = await directUpstream(bridge, `/mesh/${encodeURIComponent(name)}`);
      assert.deepEqual(mesh.data, directMesh.data);
      // Bridge read vs parsed source STL (positions + triangle indices).
      const stl = readBinaryStl(slabStl);
      assert.equal(stl.tris.length, mesh.data.tris.length);
      for (let i = 0; i < stl.positions.length; i++) {
        assert.equal(stl.positions[i], mesh.data.positions[i], `position ${i} diverged`);
      }
      for (let i = 0; i < stl.tris.length; i++) {
        assert.deepEqual(stl.tris[i], mesh.data.tris[i], `triangle ${i} diverged`);
      }

      // /project — project read carries the object list, groups + revision.
      const project = await bridgeGet(base, bridge.token, "/project");
      assert.equal(project.status, 200);
      assert.equal(project.data.ok, true);
      assert.equal(project.data.state, "ready");
      assert.equal(project.data.project.meshCount, 1);
      assert.equal(project.data.project.objects[0].name, name);

      // Zero write paths: POST /objects → 405 (read-only R0).
      const write = await bridgeGet(base, bridge.token, "/objects", { method: "POST" });
      assert.equal(write.status, 405);
      assert.equal(write.data.ok, false);

      // Unknown route: GET /nope → 404.
      const missing = await bridgeGet(base, bridge.token, "/nope");
      assert.equal(missing.status, 404);
      assert.equal(missing.data.ok, false);

      // Token gate: no token → 401; wrong token → 401.
      const noToken = await fetch(`${base}/health`, { method: "GET" });
      assert.equal(noToken.status, 401);
      const bad = await fetch(`${base}/health`, {
        method: "GET",
        headers: { "X-Bridge-Token": "00000000000000000000000000000000" },
      });
      assert.equal(bad.status, 401);
    } finally {
      await bridge.close();
    }
  },
);

test(
  "S6-005 stale upstream is a clean unavailable state, never a crash",
  { timeout: 60000 },
  async () => {
    const bridge = await startBridge({});
    const base = bridgeBase(bridge.url);
    try {
      assert.equal(bridge.state, "ready");
      // Kill the preserved server child (the bridge owns the MCP transport).
      await bridge.killUpstream();
      // Give the transport close event a beat to mark the bridge unavailable.
      await new Promise((r) => setTimeout(r, 500));
      // Every route reports unavailable — never a fallback or crash.
      const health = await bridgeGet(base, bridge.token, "/health");
      assert.equal(health.status, 200);
      assert.equal(health.data.ok, false);
      assert.equal(health.data.state, "unavailable");
      const objects = await bridgeGet(base, bridge.token, "/objects");
      assert.equal(objects.status, 502);
      assert.equal(objects.data.ok, false);
      assert.equal(objects.data.state, "unavailable");
      assert.match(objects.data.error, /legacy server not running/);
      const mesh = await bridgeGet(base, bridge.token, `/mesh/slab-20mm`);
      assert.equal(mesh.status, 502);
      assert.equal(mesh.data.state, "unavailable");
    } finally {
      await bridge.killUpstream().catch(() => {});
      await bridge.close().catch(() => {});
    }
  },
);
